apiVersion: apps/v1
kind: Deployment
metadata:
  name: notas-service
  namespace: sga
  labels:
    app: notas-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notas-service
  template:
    metadata:
      labels:
        app: notas-service
    spec:
      serviceAccountName: sga-serviceaccount
      containers:
        - name: notas
          image: emeday17/notas:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          envFrom:
            - secretRef:
                name: sga-secrets

---

apiVersion: v1
kind: Service
metadata:
  name: notas-service
  namespace: sga
spec:
  selector:
    app: notas-service
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
