apiVersion: apps/v1
kind: Deployment
metadata:
  name: personas-service
  namespace: sga
  labels:
    app: personas-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personas-service
  template:
    metadata:
      labels:
        app: personas-service
    spec:
      serviceAccountName: sga-serviceaccount
      containers:
        - name: personas
          image: emeday17/personas:1.0.0
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "mysql.sga.svc.cluster.local"
          ports:
            - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: personas-service
  namespace: sga
spec:
  selector:
    app: personas-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
