apiVersion: apps/v1
kind: Deployment
metadata:
  name: personas-service
  namespace: sga
  labels:
    app: personas-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personas-service
  template:
    metadata:
      labels:
        app: personas-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "notas-hexagonal-role"
        vault.hashicorp.com/agent-inject-secret-config: "kv/data/notas-hexagonal/personas"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "kv/data/notas-hexagonal/personas" -}}
          APP_NAME="Personas Service"
          APP_ENV={{ .Data.data.APP_ENV }}
          DB_HOST={{ .Data.data.DB_HOST }}
          DB_PORT={{ .Data.data.DB_PORT }}
          DB_USER={{ .Data.data.DB_USER }}
          DB_PASSWORD={{ .Data.data.DB_PASS }}
          DB_NAME={{ .Data.data.DB_NAME }}
          JWT_SECRET_KEY={{ .Data.data.JWT_SECRET }}
          ACCESS_TOKEN_EXPIRE_MINUTES={{ .Data.data.ACCESS_TOKEN_EXPIRE_MINUTES }}
          {{- end }}
    spec:
      serviceAccountName: sga-serviceaccount
      containers:
        - name: personas
          image: emeday17/personas:1.0.0
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              if [ -f /vault/secrets/config ]; then
                . /vault/secrets/config
              fi
              exec uvicorn app.main:app --host 0.0.0.0 --port 8003
          ports:
            - containerPort: 8003

---

apiVersion: v1
kind: Service
metadata:
  name: personas-service
  namespace: sga
spec:
  selector:
    app: personas-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003