apiVersion: apps/v1
kind: Deployment
metadata:
  name: academico-service
  namespace: sga
  labels:
    app: academico-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academico-service
  template:
    metadata:
      labels:
        app: academico-service
    spec:
      serviceAccountName: sga-serviceaccount
      containers:
        - name: academico
          image: emeday17/academico:latest
          ports:
            - containerPort: 8002
          envFrom:
            - secretRef:
                name: sga-secrets

---

apiVersion: v1
kind: Service
metadata:
  name: academico-service
  namespace: sga
spec:
  selector:
    app: academico-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
