apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sga

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - services/db_mysql/
  - services/iam/deploy-svc.yaml
  - services/academico/deploy-svc.yaml
  - services/personas/deploy-svc.yaml
  - services/notas/deploy-svc.yaml
  - ingress.yaml        # ðŸ‘ˆ nuevo ingress backend
