apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventos-peru-frontend
spec:
  destination:
    name: ''
    namespace: eventos-peru
    server: https://kubernetes.default.svc
  source:
    path: k8s/frontend/overlays/prod
    repoURL: https://github.com/emedayinc17/Eventos-Peru-Hexa.git
    targetRevision: emeday
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
