apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-service
  namespace: sga
  labels:
    app: iam-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam-service
  template:
    metadata:
      labels:
        app: iam-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "notas-hexagonal-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/notas-hexagonal/iam"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/notas-hexagonal/iam" -}}
          APP_ENV={{ .Data.data.APP_ENV }}
          DB_HOST={{ .Data.data.DB_HOST }}
          DB_PORT={{ .Data.data.DB_PORT }}
          DB_USER={{ .Data.data.DB_USER }}
          DB_PASS={{ .Data.data.DB_PASS }}
          DB_NAME={{ .Data.data.DB_NAME }}
          JWT_SECRET={{ .Data.data.JWT_SECRET }}
          ACCESS_TOKEN_EXPIRE_MINUTES={{ .Data.data.ACCESS_TOKEN_EXPIRE_MINUTES }}
          {{- end }}
    spec:
      serviceAccountName: sga-serviceaccount
      containers:
        - name: iam
          image: emeday17/iam:1.0.0
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              if [ -f /vault/secrets/config ]; then
                . /vault/secrets/config
              fi
              export DB_HOST="${DB_HOST}"
              export DB_PORT="${DB_PORT}"
              export DB_USER="${DB_USER}"
              export DB_PASS="${DB_PASS}"
              export DB_NAME="${DB_NAME}"
              export JWT_SECRET="${JWT_SECRET}"
              exec uvicorn app.main:app --host 0.0.0.0 --port 8001
          ports:
            - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: iam-service
  namespace: sga
spec:
  selector:
    app: iam-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
