apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sga-frontend-ingress
  namespace: sga
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: sga.172.189.58.78.nip.io  # ðŸ‘ˆ Mismo host que el backend
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sga-frontend
              port:
                number: 80