apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eventos-peru

resources:
  - ../../base

images:
  - name: eventos-iam
    newName: emeday17/iam-service
    newTag: "1.0.0"
  - name: eventos-catalogo
    newName: emeday17/eventos-catalogo
    newTag: "1.0.0"
  - name: eventos-proveedores
    newName: emeday17/eventos-proveedores
    newTag: "1.0.0"
  - name: eventos-contratacion
    newName: emeday17/eventos-contratacion
    newTag: "1.0.0"
  - name: eventos-gateway
    newName: emeday17/eventos-gateway
    newTag: "1.0.0"

