apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sga
resources:
  - ../../base

# Si más adelante quieres sobreescribir imágenes/tags para dev:
# images:
#   - name: iam
#     newName: emeday17/iam
#     newTag: "1.0.0"
#   ...
