apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace donde se desplegará todo
namespace: sga

# Incluir todos los recursos del backend definidos en base/
resources:
  - ../../base

# Puedes colocar aquí parches opcionales específicos para "dev"
# patches:
#   - path: patch-dev.yaml
#     target:
#       kind: Deployment
#       name: iam-service
