apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sga

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - ingress/ingress.yaml
  - services/db_mysql
  - services/iam/deploy-svc.yaml
  - services/academico/deploy-svc.yaml
  - services/notas/deploy-svc.yaml
  - services/personas/deploy-svc.yaml

# Image overrides are handled in overlays (dev/prod) to keep base generic.
