apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sga-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: frontend.sga.local # adjust to your DNS
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sga-frontend
                port:
                  number: 80
