apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventos-frontend
  namespace: eventos-peru
  labels:
    argocd.argoproj.io/instance: eventos-peru-frontend
  annotations:
    kubernetes.io/ingress.class: public
spec:
  ingressClassName: public
  rules:
    - host: eventos.emeday.inc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eventos-frontend
                port:
                  number: 80
