apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sga-frontend-ingress
  namespace: sga
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: sgaweb.emeday.inc          # mismo host que el backend
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sga-frontend
                port:
                  number: 80
