apiVersion: v1
kind: Service
metadata:
  name: eventos-frontend
  namespace: eventos-peru
  labels:
    app: eventos-frontend
spec:
  type: ClusterIP
  selector:
    app: eventos-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
