resources:
  - ../../base
images:
  - name: emeday17/frontend
    newTag: 1.0.0
patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: eventos-frontend
  - path: config-patch.yaml
    target:
      kind: ConfigMap
      name: frontend-config
